server:
  port: 8001

# 定义当前服务名
spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://127.0.0.1/petshop?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.tdwy.petshopproduct: debug

