server:
  port: 80

spring:
  application:
    name: zuul

zuul:
  routes:
    test:
      path: /simple/163
      url: http://www.163.com

#      product: /product/**
#
#      user: /user/**
#    base:
#      path: /**
#      serviceId: index



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

